using UnityEngine;
using System.Collections;
using System.Collections.Generic;


public class VehicleSpawnerForVeins : MonoBehaviour {

	public GameObject theNPCCar; 
	public Dictionary<string, GameObject> myObjectMap;

	// Use this for initialization
	void Start () {
	
		myObjectMap = new Dictionary<string, GameObject>();

	}
	
	// Update is called once per frame
	void Update () {
	
		//Read out the position information generated by Veins
		try
		{
		string text = System.IO.File.ReadAllText(@"C:\veinsSimConnectionToUnity\Veins\veins-4a2\veins-veins-4a2\examples\veins\test_cout.txt");
		Debug.Log (text);
		string[] stringArry = text.Split('|');
	
		Vector3 newPosition = new Vector3(float.Parse(stringArry[1]),120,float.Parse(stringArry[2]));
		

			GameObject currentNPC = null;
			if( myObjectMap.TryGetValue(stringArry[0], out currentNPC)){


				currentNPC.transform.position = newPosition;

			}

			else{

				myObjectMap.Add(stringArry[0],Instantiate(theNPCCar));
				myObjectMap[stringArry[0]].transform.position = newPosition;
			}
				
			
		
			theNPCCar.transform.position = newPosition;
		}
		catch (System.IO.IOException  ex){

			Debug.Log ("TextDatei wird gerade von Veins geschrieben");
		}
	}
}
